server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/75e32c1a-860e-4c9c-93b4-b1ab76c0a4d8/spring.security.oauth2.resourceserver.jwt.audiences=api://68933a20-7ee7-45b7-9fc5-bc5cec21c01c
